In [2]:
import pandas as pd
import os

ot = pd.read_excel('Listado OT.xlsx')

- N° Legajo: se debe completar automaticamente
- Sigla: se debe mostrar el listado de empresas con sus siglas. Si la empresa no está en la lista, el usuario debe indicarlo y luego ingresar el nombre de la empresa y sigla.
- Sector: lo ingresa el usuario
- Titulo: titulo del proyecto, lo ingresa el usuario
- Presupuesto: lo ingresa el usuario, si no tiene que lo deje vacio
- N° OT: se llenara muy rara vez, por lo general si creas un legajo no le pones nro de OT, porque el trabajo todavia no salió
- Presupuesto de Odoo si posee

In [28]:
ot.head()

,Nª Legajo,Empresa,Sigla,Sector,Cliente,Titulo,Presupuesto,Nº OT,Presupuesto Odoo,Unnamed: 9
0,282,Atanor,AT,Seguridad,Gabriel Mariani,Recertificación Equipos de Izaje,NaN,NaN,S00410_00,NaN
1,293,Welding Alloys,WA,Fabricación,Marcos Fabrizzi,Percha de Izaje Rolos,297_00,177.0,NaN,NaN
2,306,Fate O,FTO,Mantenimiento,Jose Luis Zuvilivia,Grúas Bandera 250kg,NaN,NaN,NaN,NaN
3,314,Atanor,AT,Seguridad,Gabriel Mariani,Fabricación Montacargas 1500 kg,302_00,NaN,NaN,NaN
4,315,Ternium Siderar,TSA,Transporte,Fernando Fillon,Banderitas Cruce,NaN,175.0,NaN,NaN

Ingrese las siglas de la empresa

In [30]:
empresas = ot[['Empresa','Sigla']].drop_duplicates(subset=['Sigla']).dropna().sort_values(by=['Empresa']).reset_index(drop=True)
empresas

                     Empresa Sigla
0                        AES   AES
1                 ASSA-SIJAM   SIJ
2                    Acindar    AC
3                Aluar - Sur    AL
4                     Arauco    AR
5                     Atanor    AT
6    Autocredito Fideicomiso   AFC
7                      Bunge    BG
8                       CAMM   CMM
9                        CIB   CIB
10                     COFCO    CF
11                  Cartocor   CTC
12                       DVS   DVS
13                    Damluc    DL
14  Desarrollos Industriales    DI
15                    Ecosan   ECO
16                    Fate O   FTO
17                  Fiplasto    FP
18                    Gerdau    GD
19            Grupo Albanesi   ALB
20               Grupo Arcor    GA
21               Halliburton    HB
22     Infa SA Puerto Madryn   ISA
23                   Loberaz    LO
24                      MISA    MI
25                   Marfrig   MFG
26                  Metalvos    MV
27                  Moviport    MP
28                  Pagliuca   PAG
29                     Pamsa    PM
30                 Parana SL   PSL
31                 Proglobal    PG
32                     REYSE    RY
33                    SAYTEC   SAY
34             San Miguel SA    SM
35           Servicios LIMSA   SLI
36                   Siderca    SC
37                   Sidersa    SI
38                   Ternium    TX
39  Ternium Florencio Varela   TFV
40           Ternium Siderar   TSA
41                  Testatec   TST
42                   VAIC SA   VSA
43            Welding Alloys    WA

In [31]:
print(empresas)

                     Empresa Sigla
0                        AES   AES
1                 ASSA-SIJAM   SIJ
2                    Acindar    AC
3                Aluar - Sur    AL
4                     Arauco    AR
5                     Atanor    AT
6    Autocredito Fideicomiso   AFC
7                      Bunge    BG
8                       CAMM   CMM
9                        CIB   CIB
10                     COFCO    CF
11                  Cartocor   CTC
12                       DVS   DVS
13                    Damluc    DL
14  Desarrollos Industriales    DI
15                    Ecosan   ECO
16                    Fate O   FTO
17                  Fiplasto    FP
18                    Gerdau    GD
19            Grupo Albanesi   ALB
20               Grupo Arcor    GA
21               Halliburton    HB
22     Infa SA Puerto Madryn   ISA
23                   Loberaz    LO
24                      MISA    MI
25                   Marfrig   MFG
26                  Metalvos    MV
27                  Moviport    MP
28                  Pagliuca   PAG
29                     Pamsa    PM
30                 Parana SL   PSL
31                 Proglobal    PG
32                     REYSE    RY
33                    SAYTEC   SAY
34             San Miguel SA    SM
35           Servicios LIMSA   SLI
36                   Siderca    SC
37                   Sidersa    SI
38                   Ternium    TX
39  Ternium Florencio Varela   TFV
40           Ternium Siderar   TSA
41                  Testatec   TST
42                   VAIC SA   VSA
43            Welding Alloys    WA